# Keeps dev branch up to date with main.
name: Update dev branch on push to main

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Update dev
        run: |
          git config pull.rebase false
          git config user.name "GitHub Actions Bot"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git checkout dev
          git status
          git pull origin main --ff-only
          git push
