name: Publish release

on:
  release:
    types: [published]

jobs:
  publish:
    name: "Publish"
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to NPMJS
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: |
          npm ci
          npm run test
          npm run doc
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
      - name: Deploy JS Docs to Github Pages
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: jsdocs
          CLEAN: false
          SINGLE_COMMIT: true
          TARGET_FOLDER: jsdocs
          COMMIT_MESSAGE: 'ci: Update docs'
